### ISSUE TITLE
Can "Tweets by prog_code" be made to open in a new browser window?

### ISSUE THREAD

**Issue by stephenscapelliti** [ProgressiveCoders/progcode-website#16]
Two issues:

1. The header **Tweets** is in the bottom panel of the [website](http://progcode.org/). 
Selecting the **"Tweets by prog_code"** link below the header should result in the ProgCode Twitter page opening in a new browser window, but instead navigates the current window to that URL.

2. Can we include a Twitter feed for https://twitter.com/prog_code?

**Comment by PamelaJohn** [comment]
@stephenscapelliti, I'm not sure if I'm misunderstanding your comment or if this has already been fixed.  

Re question 1: When I click on the header "**Tweets by** [@prog_code](https://twitter.com/prog_code)" it opens Twitter in a new browser window and keeps the ProgCode website open. Likewise, when I click the "View on Twitter" hyperlink in the bottom right corner beneath the Twitter feed, it also opens a new browser tab. 

Re question 2: The Twitter feed is what appears under the **Tweets** column header in the bottom right panel. It just has limited space and only shows the most recent Tweet.

**Comment by stephenscapelliti** [comment]
Thanks, Pamela. It dawned on me that the installation of Disconnect on my browser was causing the problem.
