### ISSUE TITLE
Add Magnify Progress to ProgCode website's "Featured Projects" 

### ISSUE THREAD

**Issue by PamelaJohn** [ProgressiveCoders/progcode-website#24]
**Website URL:** http://magnifyprogress.com/

If it's possible, Malous would like to include badges for the following links as well (in the place where we've previously included small badges linking to GitHub &/or Slack):
**iOS:** https://itunes.apple.com/us/app/magnify-progress/id1345672005
**Android:** https://play.google.com/store/apps/details?id=com.magnifyprogress 

**Description:** A social platform for organizations and activists to motivate everyday people to connect with each other and take progressive action.

**Logo:**
![logo magnify progress 246 px](https://user-images.githubusercontent.com/24970546/43374217-c9eaff94-936b-11e8-9588-caec52d4a3f0.png)

**Comment by baisong** [comment]
That sounds like a great new feature to have App Store buttons available on these. Would it be okay to just put the basic website/github/slack info now? Even if it's just the website?

**Comment by PamelaJohn** [comment]
That's absolutely okay for now @baisong! 

If it's a new feature, I'll create another issue for App Store buttons to be added at a later date. **Thank you so much** for your help!!

**Comment by PamelaJohn** [comment]
If it's a new feature, I'll create another issue for App Store buttons. Thanks again Oren!

**Comment by dlamoureaux** [comment]
I had to play with the dimensions of the image to make it fit right (attached below).

![magnify_progress](https://user-images.githubusercontent.com/40904443/43553765-9dd2eda4-95be-11e8-82e5-25a5ec80ad76.png)
