### ISSUE TITLE
Change Wobbly logo on the projects section

### ISSUE THREAD

**Issue by King-Mob** [ProgressiveCoders/progcode-website#42]
New wobbly logo can be found here: https://projects.invisionapp.com/boards/m/N53Q1PVTZGP#/6254131

Red background one, without any text

**Comment by PamelaJohn** [comment]
@ajhyndman this is the new issue to update Wobbly's logo! Thank you!

**Comment by ajhyndman** [comment]
Perfect.

@King-Mob I can resize and crop this logo if not, but is there a canonical version out there you'd prefer I use?  Even better if there's an SVG version.

Here's the file I found in the style guide that I'll use, if not.

![wobbly](https://user-images.githubusercontent.com/11449340/48239234-02ae5300-e383-11e8-87a9-d12c496c135d.png)

**Comment by ajhyndman** [comment]
Tell me if I should change it, but here's the (cropped) version of the logo I'm going to include in a pull request.

![wobbly_logo](https://user-images.githubusercontent.com/11449340/48240018-05f70e00-e386-11e8-9b9b-d48b9c1d3890.png)

**Comment by ajhyndman** [comment]
And a preview screenshot, for good measure:

![image](https://user-images.githubusercontent.com/11449340/48240100-59695c00-e386-11e8-9754-633638faab8b.png)

**Comment by King-Mob** [comment]
That's exactly what I had in mind, thank you!
