### ISSUE TITLE
Broken Airtable links on front facing ProgCode Toolkit

### ISSUE THREAD

**Issue by PamelaJohn** [ProgressiveCoders/progcode-website#7]
### **Broken Links:** 
[ProgCode Slack Channel List](https://airtable.com/shruhGsBZDvAZ2YMm)
Replace with: https://airtable.com/shrqBr7lsAu2HCoLi

[Add Your Project! (Airtable Edition)](https://airtable.com/shrtUvRH4HplSqKPt)
Replace with: https://airtable.com/shrx8GMGytfl2Gj0D

[ProgCode Calendar](https://airtable.com/shrFyckaO66toNH3U)
Replace with: https://airtable.com/shrIBemEGOX7y0V5p

[Project List in Airtable](https://airtable.com/shrCBvIfOadeSVRt5)
Replace with: https://airtable.com/shrx8GMGytfl2Gj0D

**Comment by PamelaJohn** [comment]
Fixed.

**Comment by stephenscapelliti** [comment]
Thank you, @PamelaJohn!
